POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9sbGlwbzIiLCJpZCI6IjYxNWJkYTA5YzJmNDU3MGRlYzVhMmYyNyIsImlhdCI6MTYzMzQxMDg3OX0.R-sOfYP-jWfVnj-m3untj4YaVtDSaeCTT9kqTVtfR7s

{
    "title": "Flowers",
    "author": "John",
    "url": "www.flowers.fi",
    "likes": 3
}